# Generated by Django 3.2.7 on 2021-12-02 09:54

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('abn_or_acn', models.CharField(choices=[('ABN', 'ABN'), ('ACN', 'ACN'), ('Not Present', 'Not Present')], default='ABN', max_length=15, verbose_name='ABN/ACN')),
                ('abn_or_acn_number', models.IntegerField(blank=True, null=True, verbose_name='ABN/ACN Number')),
                ('mobile', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: 'XXXXXXXXXX' or '(XX) XXXXXXXXXX'. Up to 12 digits allowed.", regex='^[(\\d) ]{10,15}$')])),
                ('gst_registered', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5, verbose_name='GST Registered')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Due_Diligence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event')),
                ('default_event', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InitialResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ListingForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MarketResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Serach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Exchange_Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('trust_name', models.CharField(max_length=100, verbose_name='Trust Name')),
                ('trust_type', models.CharField(choices=[('Unit', 'Unit'), ('Discretionary', 'Discretionary'), ('Hybrid', 'Hybrid'), ('SMSF', 'SMSF')], default='Unit', max_length=20, verbose_name='Trust Type')),
                ('bare_trust_details', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bare Trust Details')),
                ('documents', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('amount', models.CharField(blank=True, default=0, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter whole numbers.', regex='^[\\d\\,]*$')])),
                ('trust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.trust')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_box', models.CharField(blank=True, max_length=100, null=True, verbose_name='PO Box')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('suburb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suburb')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('post_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Code')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('mobile', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: 'XXXXXXXXXX' or '(XX) XXXXXXXXXX'. Up to 12 digits allowed.", regex='^[(\\d) ]{10,15}$')])),
                ('documents', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('individual', 'individual'), ('company', 'company'), ('trust', 'trust')], max_length=30, verbose_name='Entity Type')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.company')),
                ('individual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.individual')),
                ('trust', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.trust')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='Email')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.company')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.individual')),
                ('trust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.trust')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.category')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='documents',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.documents'),
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Complete')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.category')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_box', models.CharField(blank=True, max_length=100, null=True, verbose_name='PO Box')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('suburb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suburb')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('post_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Code')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.company')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.individual')),
                ('trust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.trust')),
            ],
        ),
    ]
